name: Continuous Integration - Run Frontend Lint

on:
    push:
        branches:
            - "**"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Setup node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "20.x"
            - name: Install dependencies
              run: |
                  cd frontend
                  npm install
            - name: Run tests
              run: |
                  cd frontend
                  npx eslint . --ext .js,.jsx,.ts,.tsx
            - name: Run build
              run: |
                  cd frontend
                  npm run build
            - name: Upload test results
              if: failure()
              uses: actions/upload-artifact@v3
              with:
                  name: test-results
                  path: web-service/test-results
            - name: Notify on failure
              if: failure()
              run: |
                  echo "Tests failed"
