on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Apply migrate script to postgres in prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "SELECT * FROM offre limit 10;" > migration.sql
            echo "PGPASSWORD=${{ secrets.DOCKER_PASSWORD }}" > .env
            docker container run --env-file .env -v ./migration.sql:/sql/migration.sql --rm --network=web postgis/postgis:16-3.4-alpine psql -h postgres-aus -p 5432 -U aus-user -d aus -f /sql/migration.sql